name: Validate Dataset Format

on:
  pull_request:
    paths:
      - "datasets.txt"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate `datasets.txt` Format
        run: |
          if ! grep -qE "^https://.*; .+; .+$" datasets.txt; then
            echo "Error: Invalid format in datasets.txt";
            exit 1;
          fi
